# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ClientApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ClientApp
  pod 'WalletConnectSwift', :git=>'https://github.com/vladyslav-iosdev/WalletConnectSwift.git', :branch=>'AlphaWallet'
  #pod 'EthereumKit', '~> 0.1'
end

target 'ServerApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	
  pod 'WalletConnectSwift', :git=>'https://github.com/vladyslav-iosdev/WalletConnectSwift.git', :branch=>'AlphaWallet'
  #pod 'EthereumKit', '~> 0.1'

  # Pods for ServerApp

end
